<expr_first_level> ::= <prop> | <logic_first_level> | <past_first_level>
<prop> ::= .prop <num_var> <comp> const_num
<logic_first_level> ::= .not <expr_first_level> | .and <expr_first_level> <expr_first_level>
<past_first_level> ::= .historically <expr_second_level> const_num const_num | .once <expr_second_level> const_num const_num | .since <expr_second_level> const_num const_num <expr_second_level>
<expr_second_level> ::= <prop> | <logic_second_level> | <past_second_level>
<logic_second_level> ::= .not <expr_second_level> | .and <expr_second_level> <expr_second_level>
<past_second_level> ::= .historically <expr_third_level_onwards> const_num const_num | .once <expr_third_level_onwards> const_num const_num | .since <expr_third_level_onwards> const_num const_num <expr_third_level_onwards>
<expr_third_level_onwards> ::= <prop> | <logic_third_level_onwards>
<logic_third_level_onwards> ::= .not <expr_third_level_onwards> | .and <expr_third_level_onwards> <expr_third_level_onwards>
<comp> ::= < | >
<num_var> ::= v_Vel | NE_dist | N_dist | NW_dist | W_dist | SW_dist | S_dist | SE_dist | E_dist
