<expr_first_level> ::= <prop> | <logic_first_level> | <past_first_level>
<prop> ::= .prop <num_var> <comp> <num>
<logic_first_level> ::= .not <expr_first_level> | .and <expr_first_level> <expr_first_level>
<past_first_level> ::= .globally <expr_second_level> <interval_symbol> <interval_symbol> | .eventually <expr_second_level> <interval_symbol> <interval_symbol> | .until <expr_second_level> <interval_symbol> <interval_symbol> <expr_second_level>
<expr_second_level> ::= <prop> | <logic_second_level> | <past_second_level>
<logic_second_level> ::= .not <expr_second_level> | .and <expr_second_level> <expr_second_level>
<past_second_level> ::= .globally <expr_third_level_onwards> <interval_symbol> <interval_symbol> | .eventually <expr_third_level_onwards> <interval_symbol> <interval_symbol> | .until <expr_third_level_onwards> <interval_symbol> <interval_symbol> <expr_third_level_onwards>
<expr_third_level_onwards> ::= <prop> | <logic_third_level_onwards>
<logic_third_level_onwards> ::= .not <expr_third_level_onwards> | .and <expr_third_level_onwards> <expr_third_level_onwards>
<num> ::= <digit> <digit>
<comp> ::= < | >
<digit> ::= 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | 0
<num_var> ::= x1
<interval_symbol> ::= <digit> <digit>
