<expr_first_level> ::= <prop> | <logic_first_level> | <past_first_level>
<prop> ::= <num_var> <comp> <num>
<logic_first_level> ::= .not <expr_first_level> | .or <expr_first_level> <expr_first_level>
<past_first_level> ::= .historically <expr_second_level> <interval_symbol> <interval_symbol> | .once <expr_second_level> <interval_symbol> <interval_symbol> | .since <expr_second_level> <interval_symbol> <interval_symbol> <expr_second_level>
<expr_second_level> ::= <prop> | <logic_second_level> | <past_second_level>
<logic_second_level> ::= .not <expr_second_level> | .or <expr_second_level> <expr_second_level>
<past_second_level> ::= .historically <expr_third_level_onwards> <interval_symbol> <interval_symbol> | .once <expr_third_level_onwards> <interval_symbol> <interval_symbol> | .since <expr_third_level_onwards> <expr_third_level_onwards> <interval_symbol> <interval_symbol>
<expr_third_level_onwards> ::= <prop> | <logic_third_level_onwards>
<logic_third_level_onwards> ::= .not <expr_third_level_onwards> | .or <expr_third_level_onwards> <expr_third_level_onwards>
<num> ::= <digit> <digit> <digit>
<comp> ::= < | >
<digit> ::= 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | 0
<num_var> ::= angle | torque | speed
<interval_symbol> ::= <digit> <digit>
